// Typed wrappers for every callable Cloud Function. The browser never talks to AI or SMS providers directly.
import { callable } from './firebase';
import {
  CALLABLES,
  type ProcessReferralRequestRequest,
  type ProcessReferralRequestResponse,
  type RegisterClinicRequest,
  type RegisterClinicResponse,
  type CancelReferralRequest,
  type CancelReferralResponse,
  type CreateReferralRequest,
  type CreateReferralResponse,
  type CreateStaffUserRequest,
  type CreateStaffUserResponse,
  type GenerateReferralPdfRequest,
  type GenerateReferralPdfResponse,
  type GenerateSummaryRequest,
  type GenerateSummaryResponse,
  type GetReferralReportRequest,
  type GetReferralReportResponse,
  type GetReferralViewRequest,
  type GetReferralViewResponse,
  type ResendReferralLinkRequest,
  type ResendReferralLinkResponse,
  type ResendSmsRequest,
  type ResendSmsResponse,
  type RevokeReferralLinkRequest,
  type RevokeReferralLinkResponse,
  type SendReferralRequest,
  type SendReferralResponse,
  type SetStaffActiveRequest,
  type SetStaffActiveResponse,
  type UpdateReferralStatusRequest,
  type UpdateReferralStatusResponse,
} from '@shared/contracts';

export const api = {
  createReferral: callable<CreateReferralRequest, CreateReferralResponse>(CALLABLES.createReferral),
  generateSummary: callable<GenerateSummaryRequest, GenerateSummaryResponse>(CALLABLES.generateSummary),
  sendReferral: callable<SendReferralRequest, SendReferralResponse>(CALLABLES.sendReferral),
  getReferralView: callable<GetReferralViewRequest, GetReferralViewResponse>(CALLABLES.getReferralView),
  updateReferralStatus: callable<UpdateReferralStatusRequest, UpdateReferralStatusResponse>(CALLABLES.updateReferralStatus),
  cancelReferral: callable<CancelReferralRequest, CancelReferralResponse>(CALLABLES.cancelReferral),
  revokeReferralLink: callable<RevokeReferralLinkRequest, RevokeReferralLinkResponse>(CALLABLES.revokeReferralLink),
  resendReferralLink: callable<ResendReferralLinkRequest, ResendReferralLinkResponse>(CALLABLES.resendReferralLink),
  resendSms: callable<ResendSmsRequest, ResendSmsResponse>(CALLABLES.resendSms),
  generateReferralPdf: callable<GenerateReferralPdfRequest, GenerateReferralPdfResponse>(CALLABLES.generateReferralPdf),
  createStaffUser: callable<CreateStaffUserRequest, CreateStaffUserResponse>(CALLABLES.createStaffUser),
  setStaffActive: callable<SetStaffActiveRequest, SetStaffActiveResponse>(CALLABLES.setStaffActive),
  getReferralReport: callable<GetReferralReportRequest, GetReferralReportResponse>(CALLABLES.getReferralReport),
  registerClinic: callable<RegisterClinicRequest, RegisterClinicResponse>(CALLABLES.registerClinic),
  processReferralRequest: callable<ProcessReferralRequestRequest, ProcessReferralRequestResponse>(CALLABLES.processReferralRequest),
};
